### ISSUE TITLE
cheddar npm package name

### ISSUE THREAD

**Issue by jamiter** [mccraveiro/cheddar#11]
Hello,

I would like to use the `cheddar` name for a package I developed for the [Cheddar](https://getcheddar.com) API.

Development on this framework seems to have stopped, so I wonder if you could release the npm package name. I think you can do this by adding an owner: https://docs.npmjs.com/cli/owner

Let me know if you're up for it and we'll figure something out.

Cheers,

Michiel

**Comment by mccraveiro** [comment]
Hey @jamiter 

You're right. The development of this framework have stopped a long time ago.
Therefore, I just added you as owner of cheddar.
Feel free to use it as you want :)

Regards,
Mateus

**Comment by jamiter** [comment]
Awesome, thanks!
